name: 'HMOS'
description: 'build HMOS libraries'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Build
      env:
        OHOS_SDK_HOME: ${{ github.action_path }}
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: ${{ github.action_path }}/run.bat
